### ISSUE TITLE
OpenTok.create_session - Unresolved reference 'role'. 

### ISSUE THREAD

**Issue by sys-git** [opentok/Opentok-Python-SDK#101]
version 2.4.1
file: opentok.py
lines 233-236

Looks like the validation code for `media_mode` and `archive_mode` have been cut-and-pasted from `create_token` - The string formatter for the OpenTokException uses 'role' which is undefined, obviously it should use the passed media_mode or archive_mode where applicable.

Please fix and release as 2.4.2

**Comment by aiham** [comment]
@sys-git Thanks for the report. Fixed in #118
