### ISSUE TITLE
New release anytime soon?

### ISSUE THREAD

**Issue by vesterbaek** [opentok/Opentok-Python-SDK#107]
The latest release still uses `X-TB-PARTNER-AUTH` authentication which is set to be deprecated in July 2017 (https://tokbox.com/developer/rest/). I see that JWT authentication is implemented on master. When is the next release planned?

**Comment by vesterbaek** [comment]
@davemun?

**Comment by davemun** [comment]
Sorry for the lack of response, I don't watch this repo as much as I should. Let me try to get you an update on the release plan.

**Comment by aiham** [comment]
@vesterbaek I'm working on this.

**Comment by aiham** [comment]
@vesterbaek Released https://pypi.python.org/pypi/opentok/2.5.0
