### ISSUE TITLE
OpenTokException should inherit from Exception

### ISSUE THREAD

**Issue by lcamacho** [opentok/Opentok-Python-SDK#114]
From python docs all user exceptions should be inherited from Exception class, at this time this is not caught by Django https://code.djangoproject.com/ticket/28244

https://github.com/opentok/Opentok-Python-SDK/blob/f6cf761eb09048e0b76127e0029acb6713e794ea/opentok/exceptions.py#L1

**Comment by aiham** [comment]
Thanks for the report.

#88 fixes this but the author hasn't responded to my request. I'll take it on myself.

**Comment by lcamacho** [comment]
@aiham thanks, when we can expect this to be in production?

**Comment by aiham** [comment]
@lcamacho v2.5.1 has been published
