### ISSUE TITLE
Session constructor does not check session_id type

### ISSUE THREAD

**Issue by jenstroeger** [opentok/Opentok-Python-SDK#116]
#### Problem

The [Session constructor](https://github.com/opentok/Opentok-Python-SDK/blob/master/opentok/session.py#L11) does not check the type of its `session_id` argument (or any other, for that matter) and it is therefore possible to assign `byte` as the Session id. But because the code assumes a Session id to be a `str` it’ll raise exceptions further downstream.

*Background:* I noticed this happening when I stored Tokbox Session data in a [Redis](https://redis.io/) store which converts `str` to `bytes`, and then simply used the stored data without [decoding](https://docs.python.org/3/library/stdtypes.html#bytes.decode) them to `str` again.

#### Repo Case

```python
Python 3.5.4 (default, Aug 12 2017, 14:45:14)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from opentok import OpenTok
>>> from opentok.session import Session
>>> from opentok import Roles
>>> sdk = OpenTok("…", "…")
>>> # Note that the argument here is a byte array holding the session id!
>>> session = Session(sdk, b"2_MX40…-UH4")
>>> session
<opentok.session.Session object at 0x1012249e8>
>>> # Now we print the session id, which is still a byte array!
>>> session.session_id  
b'2_MX40…-UH4'
>>> sdk.generate_token(session.session_id, Roles.moderator)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.5/site-packages/opentok/opentok.py", line 150,
in generate_token
    sub_session_id_bytes = sub_session_id.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
```
The [above assignment](https://github.com/opentok/Opentok-Python-SDK/blob/master/opentok/opentok.py#L150) assumes `session_id` to be a `str` and raises an exception.

#### Proposed Fix

I think it’s arguable as to whether this is a bug on the client’s side or the OpenTok code. As a minimal fix, however, I’d like to propose to extend the Session constructor as follows:
```python
# Trust that only bytes or str types are passed in, and convert bytes to str.
if isinstance(session_id, bytes):
    session_id = session_id.decode() # "ascii" or "utf-8"
self.session_id = session_id
```

**Comment by aiham** [comment]
@jenstroeger Thanks for the report. I've decided to raise an exception if a session_id is invalid to be consistent with how we've done it elsewhere in this project https://github.com/opentok/Opentok-Python-SDK/blob/169715ee1574b8a38e96baefa778a3ed6732b864/opentok/opentok.py#L132
