### ISSUE TITLE
OpenTok.start_archive() doesn't have parameter 'resolution'

### ISSUE THREAD

**Issue by hust-whw** [opentok/Opentok-Python-SDK#121]
OpenTok.start_archive() doesn't have parameter 'resolution'. Python SDK is simply through requests.post to use Opentok REST API and it doesn't pass the parameter 'resolution' in the payload json which is default of '640x480'.

**Comment by msach22** [comment]
@hust-whw We're aware of this and plan on updating the SDK to support the resolution parameter. If you're up for it, please feel free to contribute and send a PR 😄

**Comment by maikthomas** [comment]
Closing this issue as the work is now in a formal API proposal and PR in review, follow issue #125 and PR #124 for updates.
