### ISSUE TITLE
API proposal: get list of Streams from a Session

### ISSUE THREAD

**Issue by normanargueta** [opentok/Opentok-Python-SDK#133]
This is a proposal to add a new OpenTok Python SDK method for getting all streams info.

### opentok.get_streams()

This method returns a List of Streams, each Stream object contains information of an OpenTok stream as is described in the [documentation](https://tokbox.com/developer/rest/#get-stream-info).

### Usage

```python
session_id = 'SESSIONID'

# To get all streams in a session:
stream_list = opentok.get_streams(session_id)

# To get all streams info from a Session instance:
stream_list = session.get_streams()

# Getting the first stream of the list
stream = stream_list[0]

# Stream properties:
print stream.id #8b732909-0a06-46a2-8ea8-074e64d43422
print stream.videoType #camera
print stream.name #stream name
print stream.layoutClassList #['full']
```

**Comment by msach22** [comment]
This has been released with 2.7.0
