### ISSUE TITLE
API proposal: Update Archive Layout

### ISSUE THREAD

**Issue by normanargueta** [opentok/Opentok-Python-SDK#138]
This is a proposal to add a new OpenTok Python SDK method to change the layout of the archives dynamically.

### opentok.set_archive_layout(archive_id, type, stylesheet)

For composed archives, you can change the layout dynamically. See [docs](https://tokbox.com/developer/rest/#change-stream-layout-classes-composed).

### Usage

``` python
# The values for type could be:
# 'custom', 'horizontalPresentation', 'pip' and 'verticalPresentation'
opentok.set_archive_layout('ARCHIVEID', 'horizontalPresentation')

# If you specify a `custom` layout type, set the stylesheet parameter
opentok.set_archive_layout(
   'ARCHIVEID',
   'custom',
   'stream.instructor {position: absolute; width: 100%;  height:50%;}'
)
```

**Comment by msach22** [comment]
Released with 2.8.0
