### ISSUE TITLE
API proposal: SIP Dial

### ISSUE THREAD

**Issue by normanargueta** [opentok/Opentok-Python-SDK#142]
This is a proposal to add a new OpenTok Python SDK method to connect a SIP platform to an OpenTok session.

### opentok.dial(session_id, token, sip_uri, options)

The audio from the end of the SIP call is added to the OpenTok session as an audio-only stream. The OpenTok Media Router mixes audio from other streams in the session and sends the mixed audio to the SIP endpoint.

### Usage

```python
session_id = u('SESSIONID')
token = u('TOKEN')
sip_uri = u('sip:user@sip.partner.com;transport=tls')

# call the method with the required parameters
sip_call = opentok.dial(session_id, token, sip_uri)

# the method also support aditional options to establish the sip call

options = {
    'from': 'from@example.com',
    'headers': {
        'headerKey': 'headerValue'
    },
    'auth': {
        'username': 'username',
        'password': 'password'
    },
    'secure': True
}

# call the method with aditional options
sip_call = opentok.dial(session_id, token, sip_uri, options)
```

**Comment by msach22** [comment]
Released with v2.9.0
