### ISSUE TITLE
Initial archive layout not supported?

### ISSUE THREAD

**Issue by caffodian** [opentok/Opentok-Python-SDK#160]
According to https://tokbox.com/developer/guides/archiving/layout-control.html#specifying-the-initial-layout-type it should be possible to set the initial archive layout on creation, but the Python SDK does not implement this and you have to do the layout call afterwards.

(The broadcast ID, because it just takes a dictionary rather than kwargs that translate to parts of the payload, does not have this issue) 

Thanks for all you do!

**Comment by superdiana** [comment]
@caffodian thank you for your input this is something we will be working on!

**Comment by caffodian** [comment]
> @caffodian thank you for your input this is something we will be working on!

Great, thank you.  Do you know when this is going to be released? Don't want to duplicate work to work around it, but this is a bit flaky right now making multiple API calls.

**Comment by caffodian** [comment]
Nice to see there is a new SDK update!  Are there currently any plans to update to address this issue as well as the new screenshareType option? I may work on this

**Comment by superdiana** [comment]
Hi!! We have a couple more things coming up on minor releases within the
next couple of weeks, Including changes to the archiving layout. If there's
a solution you would like to propose I would love to see it.

**Comment by caffodian** [comment]
> @caffodian Hi!! We have a couple more things coming up on minor releases within the next couple of weeks, including changes to the archiving layout. If there's a solution you would like to propose I would love to see it.

That seems good. In my case, I can remove a lot of complexity (and get a better user experience) by switching to the new separate screenshareLayout argument that's available in the REST API, so I'll take a stab at updating what's there to support any missing arguments for now.

**Comment by caffodian** [comment]
Ah, I remember why this is ugly now.  The start_broadcast technically supports the new screen share layout option already (since it just merges a dict of options in) but the start_archive current method signature wouldn't support that.  Without messing with things too much, I'm just going to allow passing in a layout for the archive as well.

**Comment by dragonmantank** [comment]
Hello @caffodian! Just wanted to check if you were still working on this and, if so, if you think you might be done by the end of the week. No pressure though, otherwise we'll handle it internally. Either way I appreciate any help and I can ping you once we get it pushed up so you can test if we handle it.

**Comment by caffodian** [comment]
> Hello @caffodian! Just wanted to check if you were still working on this and, if so, if you think you might be done by the end of the week. No pressure though, otherwise we'll handle it internally. Either way I appreciate any help and I can ping you once we get it pushed up so you can test if we handle it.

I have something that sort of works. The past week hasn't been good for finding some focused coding time. Just need to add some tests as well.

**Comment by dragonmantank** [comment]
This has gone out as 3.1.0!
