### ISSUE TITLE
generate Sphinx docs and host the output on a gh-pages branch

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-Python-SDK#18]
in order to generate from the docstrings in the source: http://sphinx-doc.org/ext/autodoc.html

tip on getting this to work on the gh-pages branch: http://stackoverflow.com/questions/1553800/how-to-upload-html-documentation-generated-from-sphinx-to-github

link to this from README.md

**Comment by superdiana** [comment]
Will close as inactive
