### ISSUE TITLE
support & test only on more recent Python versions?

### ISSUE THREAD

**Issue by caffodian** [opentok/Opentok-Python-SDK#187]
One thing I encountered while working on the tail end of #160 is that surprisingly, the tox tests only run on 2.6, 2.7, 3.4, and 3.5, all of which are deprecated versions of Python. There's also a number of test conditions that are dependent on Python-specific JSON ordering behaviour between Python 2 & 3.

Which versions does the SDK need to actually support?  I ended up working around this by just manually running the tests against 3.9, but this probably isn't ideal. I know when it comes to Enterprise stuff you probably can't drop versions as quickly as other packages, but supporting 2.6 seems unintended. :)

**Comment by dragonmantank** [comment]
You are correct, it looks like the older versions, especially the 2.x line, were never dropped from this SDK. With it being 2021 I'm fine dropping support to 3.6+, which will bring it in line with our Vonage Python SDK (or will bring it in line soon, I'll be dropping 3.4 and 3.5 support from that one here relatively soon).
