### ISSUE TITLE
list_streams throws when there are no streams in the session yet

### ISSUE THREAD

**Issue by vineus** [opentok/Opentok-Python-SDK#211]
When there is no one in a session, the API URL:

```
https://api.opentok.com/v2/project/<project id>/session/<session id>/stream
```

returns an HTTP 404 error

## current situation

currently in this case the `list_streams()` method throws with a generic error:

https://github.com/opentok/Opentok-Python-SDK/blob/290fdefdff173858a7cba017047f555d5c6c3096/opentok/opentok.py#L991-L992

## expected behaviour

returns a `StreamList` with 0 stream

**Comment by maxkahan** [comment]
Added into #210
