### ISSUE TITLE
Bug with SIP dial after version 3.6.0

### ISSUE THREAD

**Issue by vadini-agrawal** [opentok/Opentok-Python-SDK#247]
Hi! We have found a bug with the SIP dial functionality after version 3.6.0.

We believe the bug happens after the commit here: https://github.com/opentok/Opentok-Python-SDK/commit/ff0314772c0ffec093e92f10ceeb419a51e8aa16

Previously, would store the SIP options into payload["sip"], but now it just does payload.update(options) which breaks how options is treated since the expected "options" format is:
```
options = {
    'from': 'from@example.com',
    'headers': {
        'headerKey': 'headerValue'
    },
    'auth': {
        'username': 'username',
        'password': 'password'
    },
    'secure': True,
    'video': True,
    'observeForceMute': True,
    'streams': ['stream-id-1', 'stream-id-2']
}
```
instead of 
```
options = {
   'sip': {
    'from': 'from@example.com',
    'headers': {
        'headerKey': 'headerValue'
    },
    'auth': {
        'username': 'username',
        'password': 'password'
    },
    'secure': True,
    'video': True,
    'observeForceMute': True,
    'streams': ['stream-id-1', 'stream-id-2']
  } 
}
```
Thus, if we use the SDK dial function after version 3.6.0, the options don't get loaded correctly and we aren't able to successfully make a call, unless we change the "options" structure to have "sip" as the key.

**Comment by maxkahan** [comment]
Hi, thanks for raising this. I'll get a fix out this week.
