### ISSUE TITLE
Show importing of MediaModes class in usage examples (docs)

### ISSUE THREAD

**Issue by malexh** [opentok/Opentok-Python-SDK#47]
I'm using python 3.4 and Opentok's 2.2.1 from PyPI.  I am able to successfully create a normal session with just 
    
    session = opentok.create_session()

A session gets properly created and I get a session ID in the response.

The problem starts when I try to create a session that is forced to relayed.  I want to connect a group of mobile devices from the start, so it makes sense to just initialize the session as relayed.  When using your example docs,
    
    session = opentok.create_session(media_mode=MediaModes.relayed)

throws a NameError exception that *MediaModes* isn't defined.

If I skip your docs and pass it as variables:

    location = None
    media_mode = "MediaModes.routed"    
    session = opentok.create_session(location, media_mode)

throws an exception as well:

    raise OpenTokException(u('Cannot create session, {0} is not a valid media mode').format(role))
    NameError: name 'role' is not defined

Another note - your method comments mix MediaMode and MediaModes (singular/plural).

**Comment by aoberoi** [comment]
Did you import the `MediaModes` class?

```python
from opentok import OpenTok, MediaModes

opentok = OpenTok(api_key, api_secret)
session = opentok.create_session(media_mode=MediaModes.relayed)
```

**Comment by malexh** [comment]
Sorry, I'm just getting back to this.  Importing MediaModes works, so you can close this out.  I suggest clarifying that in your examples, though.

**Comment by aoberoi** [comment]
@malexh glad that worked out for you. i agree that the examples could be clearer, thanks for that feedback.
