### ISSUE TITLE
control default timeout

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-Python-SDK#56]
also a request that came in on opentok-node, but makes sense to add here too.

**Comment by coulix** [comment]
:+1:

**Comment by vesterbaek** [comment]
Yes, having configurable timeouts on all outgoing requests are a must. We regularly see requests hanging that should have been stopped earlier by a timeout

**Comment by aiham** [comment]
@vesterbaek It looks like the issue that was blocking #57 is resolved. We can take a look at this again.

Would anyone like to take ownership of #57 and move it forward? Thanks

**Comment by vesterbaek** [comment]
@aiham. Sounds good. Getting this in is quite important for handling hanging requests, blocking a worker queue ...

**Comment by vesterbaek** [comment]
bump @aiham

**Comment by tylergould** [comment]
Hi @aiham -- have picked up your PR and made the test-related updates in https://github.com/opentok/Opentok-Python-SDK/pull/117 -- please let me know if I can do anything else to help push this forward

**Comment by aiham** [comment]
Thanks to @tylergould it looks like this is complete, I'll publish a new release now.

**Comment by aiham** [comment]
Released v2.6.0
