### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by diyan** [opentok/Opentok-Python-SDK#6]
Hello,

My employer uses OpenTok API and I've developed some code in Python 2.7 using this SDK.

We are considering move from Python 2.7 to Python 3.3 and we need this SDK ported on Python 3.

Do you have any plans on Python 3 support?

If no I can do a port by myself but before doing anything would like to double check that you are accepting pull requests.

In general I was thinking about following plan:

1. Setup Travis-CI project and ensure that all tests are passing for Python 2.7

2. Switch SDK into well-known requests library which solves all edge cases related to HTTP communication and has support for both Python 2 and 3.

3. Port all code by adding simple compat.py module (as an option six package could be used)

Please let me know your thoughts on this topic.

**Comment by aoberoi** [comment]
@diyan: i know this issue is ages old, but i wanted you to know that python 3 is supported and has been for quite some time. we followed mostly the route you explained above. if you have any feedback, please let us know.

**Comment by diyan** [comment]
@aoberoi Thank you for update. Actually we are using opentok==2.2.1 for a while and it works perfectly for us.

My fault - I had to update the status of this ticket. Sorry about that.
