### ISSUE TITLE
voice only archives, change naming to snake case

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-Python-SDK#61]
the current WIP branch for archiving_updates uses the parameter names `hasAudio` and `hasVideo`, but they should be `has_audio` and `has_video`

**Comment by ggarber** [comment]
Also outputMode at least.  Plz review all the params.

**Comment by aoberoi** [comment]
fixed in 3b3b279701023a99cec82ba0b2d3a57f8aa454fa
