### ISSUE TITLE
Failing tests: dev dep "sure" dropped support for Python 2.6, 3.2

### ISSUE THREAD

**Issue by davemun** [opentok/Opentok-Python-SDK#85]
2.6:
Some tests use the `expect` function from the `sure` module. Sure no longer supports Python 2.6 (sometime since our last build and now) and currently tests fail trying to run tox in Python 2.6.

ERROR: Failure: ImportError (cannot import name OrderedDict)
File "Opentok-Python-SDK/tests/test_archive_api.py", line 4, 
File "Opentok-Python-SDK/tests/test_archive.py", line 4,
File "Opentok-Python-SDK/tests/test_session_creation.py", line 5

OrderedDict is from Python 2.7.

3.2:
`$ pip install -r test_requirements.txt` fails with: 
`sure does explicitly not support the following python versions due to big incompatibilities: ((3, 0), (3, 1), (3, 2))`

**Comment by aoberoi** [comment]
perhaps we can consider migrating to this? https://github.com/vesln/robber.py

**Comment by aoberoi** [comment]
https://travis-ci.org/jaimegildesagredo/expects
