### ISSUE TITLE
Add support for Moderation API

### ISSUE THREAD

**Issue by ggarber** [opentok/Opentok-Python-SDK#96]
This is a request for comments regarding the API for upcoming platform functionality. The platform functionality is not generally available at the moment and there is no guarantee it will be released in any form.
### Disconnect a participant from the session

``` python
# For example to disconnect a participant when he joins the session:
@app.route("/callback", methods = ['POST'])
def connection_created(self):
   content = request.json
   if content.event === 'connectionCreated':
     opentok.force_disconnect(content.sessionId, content.connection.id)
```

**Comment by msach22** [comment]
Released with 2.7.0
